services:
  rmq1:
    image: rabbitmq:3.12-management
    hostname: rmq1
    container_name: rmq1
    networks:
      - rabbit_cluster
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_prometheus &&
        rabbitmq-server"

  rmq2:
    image: rabbitmq:3.12-management
    hostname: rmq2
    container_name: rmq2
    networks:
      - rabbit_cluster
    ports:
      - "5673:5672"
      - "15673:15672"
    depends_on:
      - rmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_prometheus &&
        sleep 10;
        rabbitmq-server &
        sleep 20;
        rabbitmqctl stop_app;
        rabbitmqctl join_cluster rabbit@rmq1;
        rabbitmqctl start_app;
        tail -f /dev/null"

  rmq3:
    image: rabbitmq:3.12-management
    hostname: rmq3
    container_name: rmq3
    networks:
      - rabbit_cluster
    ports:
      - "5674:5672"
      - "15674:15672"
    depends_on:
      - rmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_prometheus &&
        sleep 10;
        rabbitmq-server &
        sleep 20;
        rabbitmqctl stop_app;
        rabbitmqctl join_cluster rabbit@rmq1;
        rabbitmqctl start_app;
        tail -f /dev/null"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - rabbit_cluster

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      - rabbit_cluster

networks:
    rabbit_cluster:
        driver: bridge

volumes:
  prometheus_data:
  grafana_data:
