services:
  rmq1:
    image: rabbitmq:3.12-management
    hostname: rmq1
    container_name: rmq1
    networks:
      - rabbitmq_cluster
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  rmq2:
    image: rabbitmq:3.12-management
    hostname: rmq2
    container_name: rmq2
    networks:
      - rabbitmq_cluster
    ports:
      - "5673:5672"
      - "15673:15672"
    depends_on:
      - rmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    command: /bin/bash -c "sleep 10; rabbitmq-server & sleep 20; rabbitmqctl stop_app; rabbitmqctl join_cluster rabbit@rmq1; rabbitmqctl start_app; tail -f /dev/null"

networks:
    rabbitmq_cluster:
        driver: bridge