global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rmq1:15692', 'rmq2:15692']
    metrics_path: /metrics
    scheme: http
    basic_auth:
      username: admin
      password: admin

  - job_name: 'spring-receiver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] 