{
 "title": "RabbitMQ Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(rabbitmq_identity_info)" }
   ]
  },
  {
   "title": "Average Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_message_processing_time_seconds_sum[5m]) / rate(rabbitmq_message_processing_time_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Message Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_message_latency_seconds_sum[5m]) / rate(rabbitmq_message_latency_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "rabbitmq_messages_received" }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "rabbitmq_messages_sent" }
   ]
  }
 ]
}