spring:
  rabbitmq:
    addresses: localhost:5672,localhost:5673,localhost:5674
    username: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: misemilia01@gmail.com
    password: hqsyuzrtvbudjids
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    enable:
      jvm: true
      process: true
      system: true
      rabbitmq: true

queue:
  logs: error-logs-queue

