spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: misemilia01@gmail.com
    password: hqsyuzrtvbudjids
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
queue:
  name: my-queue
  logs: error-logs-queue

